  target_prompt_template: >
    Ваша задача – извлечь точные значения для строго определенного списка сущностей из текста. Все указанные сущности должны быть включены в ответ, даже если они отсутствуют в тексте.

    1. Изучите описания сущностей, которые передаются через "|" после названий сущностей. Они помогут лучше понять, что нужно извлечь из текста. ДОБАВЛЯТЬ ИХ В ОТВЕТ СТРОГО ЗАПРЕЩЕНО. Если описаний нет, переходите к следующему шагу.
    2. Извлеките из текста документа значение для каждой сущности из списка.
    3. Проверьте, что список сущностей в ответе соответствует приведенному ниже списку, без добавления или пропуска каких-либо сущностей.
    4. Сформируйте ответ строго в формате "название поля: описание поля\n", где ключи - названия полей, значения - извлеченные поля из текста. Если значение для какой-либо сущности отсутствует в тексте, укажите "Не найдено" рядом с её названием. При выводе ответа используй "\n" только для разделения описаний сущностей. 
    ЗАПРОС:

    Список сущностей:
    {entities}

    Текст документа:
    {query}

    Извлеченные сущности:

  task_description_init: >
    Создай набор кратких, точных и информативных описаний для различных типов именованных сущностей (NER). 

    Эти описания будут использоваться в системах NER для определения и классификации сущностей в тексте. Для каждого типа сущности нужно создать четкое определение, которое:

    1. Точно описывает, что представляет собой данный тип сущности
    2. Указывает характерные признаки для распознавания этого типа
    3. Приводит границы и ограничения (что включается, а что нет)
    4. Содержит 1-2 примера типичных представителей
    5. ОБЯЗАТЕЛЬНО приводит слова или фразы, которые часто встречаются вместе с этими сущностями
    6. Указывает, в каком месте документа встречается данная сущность
    7. Указывает формат, в котором нужно вернуть данную сущность(формат должен быть как в разметке)
    8. ОБЯЗАТЕЛЬНО приводит типичный отрывок текста, в котором встречается данная сущность и что из этого отрывка текста нужно извлечь
    9. Приводит альтернативные названия для этого поля  

    Обязательно учти пункт 8.
    Все приведенные пункты должны быть написаны в описании сущности. 
    Также в описании поля можно добавить альтернативные названия поля через "|".

    Необходимо создать описания для следующих типов сущностей:
    {entities_names}

    {examples}

    Описания должны быть лаконичными (не более 3-4 предложений), но при этом достаточно информативными для однозначной классификации. Они будут использоваться как справочные определения для моделей машинного обучения и аннотаторов данных.
    Сформируйте ответ строго в формате "название поля: описание поля\n", где ключи - названия полей, значения - описания полей. При выводе ответа используй "\n" только для разделения описаний сущностей. 

  task_description_iterative: > 
    Изучите описания сущностей, которые передаются через "|" после названий сущностей. Улучшите варианты описаний для указанных описаний сущностей. 
    Обратите особое внимение на те поля, у которых F1 ниже, чем у других, найди причину ошибок и поменяй описание сущности.
    Убедись, что описания корректны, если это не так - поменяй их, предложи другой вариант описания.

    Эти описания будут использоваться в системах NER для определения и классификации сущностей в тексте. Для каждого типа сущности нужно создать четкое определение, которое:

    1. Точно описывает, что представляет собой данный тип сущности
    2. Указывает характерные признаки для распознавания этого типа
    3. Приводит границы и ограничения (что включается, а что нет)
    4. Содержит 1-2 примера типичных представителей
    5. ОБЯЗАТЕЛЬНО приводит слова или фразы, которые часто встречаются вместе с этими сущностями
    6. Указывает, в каком месте документа встречается данная сущность
    7. Указывает формат, в котором нужно вернуть данную сущность(формат должен быть как в разметке)
    8. ОБЯЗАТЕЛЬНО приводит типичный отрывок текста, в котором встречается данная сущность и что из этого отрывка текста нужно извлечь
    9. Приводит альтернативные названия для этого поля 

    Обязательно учти пункт 8.
    Все приведенные пункты должны быть написаны в описании сущности. 

    Необходимо улучшить следующие описания:
    {entities_names_discriptions}

    {examples_with_preds}

    Описания должны быть лаконичными (не более 3-4 предложений), но при этом достаточно информативными для однозначной классификации. Они будут использоваться как справочные определения для моделей машинного обучения и аннотаторов данных.
    Сформируйте ответ строго в формате "название поля: описание поля\n", где ключи - названия полей, значения - описания полей. При выводе ответа используй "\n" только для разделения описаний сущностей. 

  calc_metrics_prompt: >
    Ты выступаешь в роли эксперта, оценивающего качество ответа на заданный вопрос.
    
    У тебя есть:
    - Эталонный (правильный) ответ.
    - Предсказанный ответ модели.
    
    Твоя задача — определить, является ли предсказанный ответ правильным по смыслу, даже если он отличается по формату или формулировке.
    
    ОЦЕНИВАЙ ПРЕДСКАЗАНИЕ СЛЕДУЮЩИМ ОБРАЗОМ:
    1. Если предсказанный ответ эквивалентен эталонному по смыслу, даже если отличается по стилю, формату, пунктуации или структуре — считай его верным.
    2. Если ответ содержит смысловые ошибки, — считай его неверным.
    3. Игнорируй:
       - Переформулировки;
       - Синонимы;
       - Разный порядок слов;
       - Разные способы форматирования (дата, число, пунктуация), если они не меняют смысл.
       - Сокращения
    4. Если ответ модели содержит правильный ответ, но при этом в ответе модели есть лишняя информация или лишние элементы,  — считай ответ верным.
    ИГНОРИРУЙ ЛИШНИЕ ЭЛЕМЕНТЫ, ЕСЛИ В ПРЕДСКАЗАНИИ ЕСТЬ ВЕРНЫЙ ОТВЕТ.
    Нужно вернуть true(ответы совпадают) или false(ответы не совпадают). 
    ОТВЕТ ВЫДАВАЙ В ФОРМАТЕ: "ОТВЕТ: true/false"

    Описание: {desc}
    
    Предсказание: {prediction}
    
    Ожидаемый ответ: {ground_truth}
